# Generated by Django 5.0.2 on 2024-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('test_result', models.IntegerField()),
                ('info', models.TextField()),
            ],
        ),
    ]
