# Generated by Django 5.0.2 on 2024-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearmind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
