# Generated by Django 5.0.2 on 2024-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearmind', '0004_alter_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer_choice_1', models.CharField(max_length=255)),
                ('answer_choice_1_points', models.IntegerField(default=0)),
                ('answer_choice_2', models.CharField(max_length=255)),
                ('answer_choice_2_points', models.IntegerField(default=0)),
                ('answer_choice_3', models.CharField(max_length=255)),
                ('answer_choice_3_points', models.IntegerField(default=0)),
                ('answer_choice_4', models.CharField(max_length=255)),
                ('answer_choice_4_points', models.IntegerField(default=0)),
            ],
        ),
    ]
