# Generated by Django 5.0.2 on 2024-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearmind', '0006_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='type',
            field=models.CharField(choices=[('Meditation', 'meditation'), ('Affirmation', 'affirmation'), ('Breathing', 'breathing')], default='Meditation', max_length=100),
        ),
    ]
