# Generated by Django 5.0.2 on 2024-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearmind', '0007_useractivity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='video',
            field=models.URLField(default='https://www.youtube.com/watch?v=inpok4MKVLM&t=9s'),
        ),
    ]
