# Generated by Django 5.0.2 on 2024-05-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearmind', '0008_alter_data_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='video',
            field=models.URLField(default='inpok4MKVLM?si=z5AnJ_9QMKE3POno'),
        ),
    ]
