# Generated by Django 5.0.2 on 2024-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearmind', '0009_alter_data_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='video',
        ),
        migrations.AddField(
            model_name='data',
            name='video_id',
            field=models.CharField(default='inpok4MKVLM', max_length=100),
        ),
    ]
