# Generated by Django 5.0.2 on 2024-05-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearmind', '0010_remove_data_video_data_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.URLField(default='default_image.jpg'),
        ),
    ]
